# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f187deba689320b8f7631b4cf85a59570953d5804bdfb87317ae0ef17fe4af7b8c19ee14dbba07455e56106a390c1060faa039334b1d77820ec3958212ecfba2

test:
  secret_key_base: e93efda212cb1c84ba75e32f3e882ecc4d123dd701ad2122317906a677fcad34dbe91ab7d9e7d8ebf60bdb462031442b96ea997949f8b9244b467330775d27ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
